name: task1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  signature: ^4.1.1
  shared_preferences: ^2.0.15
  path_provider: ^2.1.4
  hand_signature: ^3.0.3
  flutter_svg: ^1.1.6
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

